name = "io_utils"
description = "A terminal IO library"
version = "1.0.0"
licenses = "GPL-3.0-only"

authors = ["Dylan E."]
maintainers = ["Dylan E. <76961140+KvanQuilst@users.noreply.github.com>"]
maintainers-logins = ["kvanquilst"]
